### ISSUE TITLE
Is 3.5.1 Note on matplotlib compatibility still necessary?

### ISSUE THREAD

**Issue by elisehellwig** [ucdavisdatalab/workshop_python_basics#6]
In section 3.5.1 on installing and importing `plotnine`, it mentions that you need to install `matplotlib<3.6` because `plotnine` is incompatible with later versions of `matplotlib`. It seems like that has been fixed now so it may be a good idea to remove the note so people don't downgrade their `matplotlib` by mistake.

**Comment by elisehellwig** [comment]
Similar issue with a Note in 3.2.1 about how the string dtype is experimental in pandas.

**Comment by nick-ulle** [comment]
The string dtype is no longer experimental, but the object dtype is still the default. So I think we should keep part of the note about the history of the object dtype. I'll do some editing today.

**Comment by nick-ulle** [comment]
Actually, looking at the docs, the string dtype is [still listed as experimental](https://pandas.pydata.org/docs/reference/api/pandas.StringDtype.html#pandas.StringDtype). So I'm just going to revert that part of your commit.

**Comment by nick-ulle** [comment]
Revert is in 3d2e97d. Also, don't forget to run `pixi run build` and `pixi run publish` when you make updates.

Closing this issue again.
